/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  ICC_Guide: [
  'intro',
  {
        type: 'category',
        label: 'Нижний ярус',
        link: {
          type: 'doc',
          id: 'lower spire/index'
        },
        items: [
          'lower spire/lord_marrowgar',
          'lower spire/lady_deathwhisper',
          'lower spire/gunship_battle',
          'lower spire/saurfang',
        ],
  },
  {
      type: 'category',
      label: 'Чумодельня',
      link: {
        type: 'doc',
        id: 'plagueworks/index'
      },
      items: [
        'plagueworks/festergut',
        'plagueworks/rotface',
        'plagueworks/putricide',
      ],
    },
    {
        type: 'category',
        label: 'Багровый зал',
        link: {
          type: 'doc',
          id: 'crimson_hall/index'
        },
        items: [
          'crimson_hall/blood_prince_council',
          'crimson_hall/lanathel',
        ],
      },
    {
        type: 'category',
        label: 'Залы Ледокрылых',
        link: {
          type: 'doc',
          id: 'frostwing_halls/index'
        },
        items: [
          'frostwing_halls/valithria',
          'frostwing_halls/sindragosa',
        ],
      },
    'the_lich_king'
  ],
  ulduar: [
  {
        type: 'autogenerated',
        dirName: 'ulduar',
      },
  ]



};

module.exports = sidebars;
